name: Artemis CI testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.2
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testing
          MYSQL_USER: sayo
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v4
    
    - name: set up Docker
      uses: docker/setup-buildx-action@v3
      
    - name: Copy .env.example
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      
    - name: Start Sail containers
      run: |
        ./vendor/bin/sail up -d
      env:
        WWWGROUP: '1000'
        
    - name: Install dependencies
      run: ./vendor/bin/sail composer install

    - name: Generate app key
      run: ./vendor/bin/sail artisan key:generate

    - name: Run database migrations
      run: ./vendor/bin/sail artisan migrate --force

    - name: Run tests
      run: ./vendor/bin/sail artisan test
